<a href="https://colab.research.google.com/github/A-kki/ML/blob/main/Copy_of_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# Import numpy and create a 1D array (vector)
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [34]:
# Create a 2D array (matrix) and display its properties
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [35]:
# Generate a sequence of numbers using np.arange
print("A series of numbers:",np.arange(5,16)) # A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [36]:
# Generate numbers with a specific step size
print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [37]:
# Generate numbers with a floating-point step size
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [38]:
# Generate numbers in reverse order with a step size
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [39]:
# Generate linearly spaced numbers using np.linspace
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,21))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


# Zeroes, Ones, empty, and Identity **matriX**

> Indented block



In [40]:
# Create arrays of zeros
print("Vector of zeroes\n---------------------")
print(np.zeros(5))
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]
Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
# Create arrays of ones and a custom value
print("Vector of ones\n---------------------")
print(np.ones(5))
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]
Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [42]:
# Create an empty matrix (uninitialized values)
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [43]:
# Create an identity matrix
mat1 = np.eye(4)
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
# Generate random numbers from a Uniform distribution
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

Random number generation (from Uniform distribution)
[[0.67433847 0.7019177  0.28660019]
 [0.50224166 0.60410608 0.14982672]]


In [45]:
# Generate random numbers from a Standard Normal distribution
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.21076284  1.31766213 -0.17819413]
 [ 1.35083841  0.60456857  0.34154797]
 [-1.12895251  0.56362304  0.28421111]
 [-0.64483736  0.08305765 -1.19236245]]


In [46]:
# Generate random integers
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [13 58 71 81 92  4 21 77 18 16]

Random integer matrix
[[27 98 28 16]
 [72 33 39 57]
 [57 24 36 93]
 [88 75 70  5]]

20 samples drawn from a dice throw: [5 1 3 5 5 6 3 2 5 4 2 5 1 4 3 5 6 1 1 1]


# Reshaping, min, max, **sort**

In [47]:
# Reshape arrays and sort them
import numpy as np
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)

A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))

M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)

a looks like
 -------------------- 
 [62 85 43  6 63 54 11  4 91  8 61 67  6 69 70 67 63 21 23 99 83 15  2 94
 69 73  7 44  8  9] 
 --------------------

b looks like
 -------------------- 
 [[[62 85 43  6 63]
  [54 11  4 91  8]
  [61 67  6 69 70]]

 [[67 63 21 23 99]
  [83 15  2 94 69]
  [73  7 44  8  9]]] 
 --------------------

c looks like
 -------------------- 
 [[62 85 43  6 63]
 [54 11  4 91  8]
 [61 67  6 69 70]
 [67 63 21 23 99]
 [83 15  2 94 69]
 [73  7 44  8  9]] 
 --------------------

Vector of random integers
 -------------------------------------------------- 
 [94 20 71 58 78 64 84 79 21  3]

Here is the sorted vector
 -------------------------------------------------- 
 [ 3 20 21 58 64 71 78 79 84 94]

5x5 Matrix of random integers
 -------------------------------------------------- 
 [[90 33 84 81 42]
 [25 65 83 25 57]
 [74 20  3 49 76]
 [37 22 34 63 20]
 [87  1 11 13 48]]

Here is the sorted matrix along eac

In [48]:
# Find maximum values and their locations in arrays
print("Max of a:", a.max())
print("Max of b:", b.max())
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a: 99
Max of b: 99
Max of a location: 19
Max of b location: 19
Max of c location: 19


In [49]:
# Demonstrate array indexing and slicing
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [50]:
# Demonstrate matrix indexing and subsetting
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[11 50 25 63 61]
 [25 49 75 80 64]
 [11 73 10 14 26]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 75

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 75

Row or column extract
----------------------
Entire row at index 2: [11 73 10 14 26]
Entire column at index 3: [63 80 14]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[80 64]
 [14 26]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[50 63]
 [49 80]]


In [51]:
# Perform element-wise operations on matrices
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[2 1 3]
 [6 1 1]
 [1 3 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 3 7]
 [3 9 5]
 [6 8 9]]

Addition
------------------
 [[10  4 10]
 [ 9 10  6]
 [ 7 11 10]]

Multiplication
------------------
 [[16  3 21]
 [18  9  5]
 [ 6 24  9]]

Division
------------------
 [[0.25       0.33333333 0.42857143]
 [2.         0.11111111 0.2       ]
 [0.16666667 0.375      0.11111111]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[-10  -3  -5]
 [ 12 -15  -7]
 [ -9  -7 -15]]

Addition of a scalar (100)
-------------------------
 [[102 101 103]
 [106 101 101]
 [101 103 101]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  8   1  27]
 [216   1   1]
 [  1  27   1]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[1.41421356 1.         1.73205081]
 [2.44948974 1.         1.        ]
 

**Broadcasting (super cool feature)**
NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

they are equal, or
one of them is 1
If these conditions are not met, a ValueError: frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

For more detail, please look up: https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [52]:
# Initialize a 2D array with zeros
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [53]:
# Create a 1D array to be broadcasted
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [54]:
# Demonstrate broadcasting a 1D array across rows of a 2D array
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [55]:
# Create a 2D array (column vector) to be broadcasted
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [56]:
# Demonstrate broadcasting a column vector across columns of a 2D array
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [57]:
# Demonstrate broadcasting a scalar across a 2D array
# this will just broadcast in both dimensions
add_scalar = np.array([100])
print(start+add_scalar)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


# Linear Algebra Operations
# Dot/Inner/Outer products

In [58]:
# Perform dot, inner, and outer products of arrays
A = np.arange(1,10).reshape(3,3)
B = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of 1-9 single-digit numbers (A)\n","-"*50,"\n",A)
print("\n2nd Matrix of random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nDot product of A and B (for 2D arrays it is equivalent to matrix multiplication) \n","-"*80,"\n",np.dot(A,B))

A = np.arange(1,6)
B = ri(1,10,5)
print("\n1st Vector of 1-5 numbers (A)\n","-"*50,"\n",A)
print("\n2nd Vector of 5 random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nInner product of vectors A and B \n","-"*50,"\n",np.inner(A,B), "(sum of all pairwise elements)")
print("\nOuter product of vectors A and B \n","-"*50,"\n",np.outer(A,B))


1st Matrix of 1-9 single-digit numbers (A)
 -------------------------------------------------- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers (B)
 -------------------------------------------------- 
 [[4 1 3]
 [9 3 9]
 [6 1 5]]

Dot product of A and B (for 2D arrays it is equivalent to matrix multiplication) 
 -------------------------------------------------------------------------------- 
 [[ 40  10  36]
 [ 97  25  87]
 [154  40 138]]

1st Vector of 1-5 numbers (A)
 -------------------------------------------------- 
 [1 2 3 4 5]

2nd Vector of 5 random single-digit numbers (B)
 -------------------------------------------------- 
 [6 3 8 2 7]

Inner product of vectors A and B 
 -------------------------------------------------- 
 79 (sum of all pairwise elements)

Outer product of vectors A and B 
 -------------------------------------------------- 
 [[ 6  3  8  2  7]
 [12  6 16  4 14]
 [18  9 24  6 21]
 [24 12 32  8 28]
 [30 15 40 10 35]]


# TRANSPOSE

In [59]:
# Demonstrate matrix transposition and multiplication with transpose
A = ri(1,10,9).reshape(3,3)
print("\n3x3 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix transpose\n","-"*50,"\n",np.transpose(A))

B = ri(1,10,6).reshape(3,2)
print("\n3x2 Matrix of random single-digit numbers\n","-"*50,"\n",B)
print("\n2x3 Matrix transpose\n","-"*50,"\n",np.transpose(B))
print("\nMatrix multiplication of B and B-transpose\n","-"*50,"\n",np.dot(B, np.transpose(B)))


3x3 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 3 1]
 [4 5 7]
 [8 9 2]]

Matrix transpose
 -------------------------------------------------- 
 [[6 4 8]
 [3 5 9]
 [1 7 2]]

3x2 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 1]
 [6 3]
 [7 1]]

2x3 Matrix transpose
 -------------------------------------------------- 
 [[4 6 7]
 [1 3 1]]

Matrix multiplication of B and B-transpose
 -------------------------------------------------- 
 [[17 27 29]
 [27 45 45]
 [29 45 50]]


In [60]:
# Calculate the trace of a matrix
A = ri(1,10,16).reshape(4,4)
print("\n4x4 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix trace\n","-"*50,"\n",np.trace(A))
print("\nMatrix trace with ofset +1 (upper triangle)\n","-"*50,"\n",np.trace(A,offset=1))
print("\nMatrix trace with ofset -1 (lower triangle)\n","-"*50,"\n",np.trace(A,offset=-1))


4x4 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 9 8 8]
 [4 4 6 6]
 [1 8 9 2]
 [2 6 3 3]]

Matrix trace
 -------------------------------------------------- 
 17

Matrix trace with ofset +1 (upper triangle)
 -------------------------------------------------- 
 17

Matrix trace with ofset -1 (lower triangle)
 -------------------------------------------------- 
 15


# **Eigenvalues and eigenvectors**

In [61]:
# Calculate eigenvalues and eigenvectors of a matrix
A = np.random.randn(9).reshape(3,3)
print("Original matrix\n",A)
print("\n")
w,v=np.linalg.eig(A)
print("Eigenvalues:\n",w)
print("\n")
print("Eigenvectors:\n",v)

Original matrix
 [[ 0.15451153 -1.55786436  0.42612675]
 [ 1.75265363 -0.32697893  0.36532617]
 [-0.25209736  0.51452432  1.80154735]]


Eigenvalues:
 [-0.1329336 +1.66575976j -0.1329336 -1.66575976j  1.89494714+0.j        ]


Eigenvectors:
 [[-0.1084983 -0.68103424j -0.1084983 +0.68103424j  0.05594283+0.j        ]
 [-0.70882578+0.j         -0.70882578-0.j          0.20479829+0.j        ]
 [ 0.14402361+0.03526621j  0.14402361-0.03526621j  0.97720421+0.j        ]]


# Linear equation solving, matrix inverse, linear least suqare
You can directly solve linear system of equations using NumPy writing only one line of code.

Suppose you want to solve the following set of equations for (x,y,z). It is easy to see that (2,1,5) are the unique solutions.

2x + 5y + z = 14;

3x - 2y - z = -1;

x - 3y + z = 4

In [62]:
# Solve a system of linear equations
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]])
B = np.array([14,-1,4])
x = np.linalg.solve(A,B)

print("The solutions are:",x)

The solutions are: [2. 1. 5.]


In [63]:
# Reshape a 1D array into a column vector
x=[1,2,3]
import numpy as np
x= np.array(x)
x.reshape(3, -1)

array([[1],
       [2],
       [3]])